server:
  port: 8060
spring:
  application:
    name: chatting-server
  redis:
    host: localhost
    port: 6379
#    timeout: 5000
#  profiles:
#    active: local
keycloak:
  auth-server-url: http://13.209.121.101:8080/auth
  realm: ddangn-market
  resource: chatting-server
  public-client: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}